---
title: "Analysing Results of Questionnaire"
author: "aiswary-a"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
output: 
  html_document:
    toc: TRUE
  pdf_document:
    toc: TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. Data Prep
## 0.1. Workspace Prep
```{r}

# loading libraries
library(pacman)
pacman::p_load(tidyverse,
               car, # for accessing Levene's test
               patchwork) # for organising graphs

```

## 0.2. Cleaning the Data

```{r, message = FALSE}

# insert CSV
df <-
  read_csv(
    "C:/Users/aisro/Desktop/UNI/BSc CogSci - 2nd Sem/Applied/VSCode + Git/Form Responses/CogSci_Applied_Responses - Form responses_USINGFORCODEPREP_2.csv"
  ) # to be updated with final data, this is just a placeholder

# renaming the df columns
## NOTE: [1] pre-tool usage, [2] post-tool usage, [char] textual response, [num] numerical response
renaming_dfCols <-
  c(
    "timestamp",
    "age",
    "vote_eligibility",
    "preTool_biasPerception",
    "preTool_biasAwareness",
    "preTool_morality",
    "preTool_valueCommitment",
    "email",
    "postTool_biasPerception",
    "postTool_biasAwareness",
    "postTool_morality",
    "postTool_valueCommitment",
    "char_engagement",
    "num_decision_enjoyment",
    "num_likely_to_recommend",
    "num_ranking_agreement",
    "char_ranking_selfperception",
    "char_past_candidate_test",
    "char_future_candidate_test",
    "char_comment_tool_selfperception",
    "char_comment_tool_design",
    "char_comment_other",
    "gender",
    "empty"
  )

colnames(df) <- renaming_dfCols

# deleting email column
df <- df %>%
  select(-email, -empty)

# removing first (test) row
df <- df[df$timestamp != "16/04/2024 14:07:03",]

# fusing the duplicated row
merged_row <-
  c(
    "01/05/2024 16:26:10",
    31,
    "Yes",
    7,
    5,
    7,
    6,
    3,
    7,
    6,
    6,
    "it was fun to go through the scenarios! I think the value descriptions are a bit abstract and hard to grasp, and my ranking had a lot of 'noise' as a function of that. perhaps a few examples, or 'simpler', more concrete value headings could help? perhaps more values would also be great. with respect to questionnaire questions, i think questions about biases were also a bit underspecified (what does it mean to be 'biased', in this context?)",
    8,
    8,
    8,
    " ",
    "Yes",
    "Yes",
    " ",
    " ",
    "",
    "Female"
  )

# now adding the merged_row to the df
df <- rbind(df, merged_row)

# getting rid of 'accidental' double response (participant age 31)
df <- df[-c(17, 18), ]

# ID'ing non-numeric columnsss and making those all lowercase!
df <- df %>% 
  mutate_if(~ !is.numeric(.), tolower)

# making sure everything that needs to be numeric IS NUMERIC!!!
columns_to_convert <- c(
  "age",
  "preTool_biasPerception", ## Pre-Tool BP
  "postTool_biasPerception", ## Post-Tool BP
  "preTool_biasAwareness", ## Pre-Tool BA
  "postTool_biasAwareness", ## Post-Tool BA
  "preTool_morality", ## Pre-Tool M
  "postTool_morality", ## Post-Tool M
  "preTool_valueCommitment", ## Pre-Tool VC
  "postTool_valueCommitment", ## Post-Tool VC
  "num_decision_enjoyment", ## tool engagement level
  "num_likely_to_recommend", # how likely to recommend
  "num_ranking_agreement" # ranking agreement level
)  

# Convert selected columns to numeric
df <- df %>%
  mutate(across(all_of(columns_to_convert), as.numeric))

```



```{r}

# groups for stat tests!

groupSingles <- c(
  "preTool_biasPerception", ## Pre-Tool BP
  "postTool_biasPerception", ## Post-Tool BP
  "preTool_biasAwareness", ## Pre-Tool BA
  "postTool_biasAwareness", ## Post-Tool BA
  "preTool_morality", ## Pre-Tool M
  "postTool_morality", ## Post-Tool M
  "preTool_valueCommitment", ## Pre-Tool VC
  "postTool_valueCommitment" ## Post-Tool VC
)

# vars. of interest :))
groupSingles <- c(
  "preTool_biasPerception", ## Pre-Tool BP
  "postTool_biasPerception", ## Post-Tool BP
  "preTool_biasAwareness", ## Pre-Tool BA
  "postTool_biasAwareness", ## Post-Tool BA
  "preTool_morality", ## Pre-Tool M
  "postTool_morality", ## Post-Tool M
  "preTool_valueCommitment", ## Pre-Tool VC
  "postTool_valueCommitment" ## Post-Tool VC
)

# defining the group pairings for the loops
groupPairs <- list(
  c("preTool_biasPerception", "postTool_biasPerception"), ## BP
  c("preTool_biasAwareness", "postTool_biasAwareness"), ## BA
  c("preTool_morality", "postTool_morality"), ## M
  c("preTool_valueCommitment", "postTool_valueCommitment") ## VC
)

# group pairings for plots!
## Bias Perception Group
gr_dfBiasPerception <- c(df$preTool_biasPerception,df$postTool_biasPerception)
grPlot_dfBiasPerception <- data.frame(
  measure = c(df$preTool_biasPerception, df$postTool_biasPerception),
  group = c("Pre-Tool BP", "Post-Tool BP")
)
grPlot_dfBiasPerception <- na.omit(grPlot_dfBiasPerception) # skipping any na's

## Bias Awareness Group
gr_dfBiasAwareness <- c(df$preTool_biasAwareness, df$postTool_biasAwareness)
grPlot_dfBiasAwareness <- data.frame(
  measure = c(df$preTool_biasAwareness, df$postTool_biasAwareness),
  group = c("Pre-Tool BA", "Post-Tool BA")
)
grPlot_dfBiasAwareness <- na.omit(grPlot_dfBiasAwareness) # skipping any na's

## Morality Level Group
gr_dfMorality <- c(df$preTool_morality, df$postTool_morality)
grPlot_dfMorality <- data.frame(
  measure = c(df$preTool_morality, df$postTool_morality),
  group = c("Pre-Tool M", "Post-Tool M")
)
grPlot_dfMorality <- na.omit(grPlot_dfMorality) # skipping any na's

## Value Commitment Level Group
gr_dfValCommitment <- c(df$preTool_valueCommitment, df$postTool_valueCommitment)
grPlot_dfValCommitment <- data.frame(
  measure = c(df$preTool_valueCommitment, df$postTool_valueCommitment),
  group = c("Pre-Tool VC", "Post-Tool VC")
)
grPlot_dfValCommitment <- na.omit(grPlot_dfValCommitment) # skipping any na's

```


# 1. Demographics
## 1.1. Sample Size
```{r}

cat("N =", nrow(df))

```

## 1.2. Age
```{r}

# age distribution

df$age <- as.numeric(df$age) # just making sure

stats_dfAge <- df %>%
  summarise(mean = mean(age), sd = sd(age)) # insert age column

print(paste("The mean age:", round(stats_dfAge$mean, digits = 3)))
print(paste("The SD of the age:", round(stats_dfAge$sd, digits = 3)))

```

## 1.3. Gender
```{r}

# gender distribution
stats_dfGender <- df %>% 
  count(gender) # insert gender column

print(paste("The gender distribution of the sample:", stats_dfGender))

```

## 1.4. Candidate Testing
```{r}

# Past Usage?
### [insert code here]

# Future Usage?
### [insert code here]

```


# 2. Pre-Tool vs. Post-Tool Usage

## 2.1. Checking Assumptions
### a. Normality
```{r}

# Shapiro-Wilk test for Normality!

stat_nResults <- list() # an empty list to store the results

# normality testing for-loop, going through each indexed column
for (i in seq_along(groupSingles)) {
  single <- groupSingles[i]  # extract column name using index
  
  # taking the group and forcing it to numeric if necessary
  item <-
    as.numeric(df[[single]])
  
  # the Shapiro-Wilk normality test!
  shapiro_result <-
    shapiro.test(item)
  
  # storing the results
  test_name <-
    paste("Shapiro-Wilk Test of Normality for", single)
  stat_nResults[[test_name]] <- shapiro_result
  
  # printing the result!
  cat(test_name, ":\n")
  print(shapiro_result)
  
  # performing the hypothesis test using results!
  if (!is.null(shapiro_result$p.value) &&
      shapiro_result$p.value > 0.05) {
    cat(
      "Fail to reject null hypothesis that data significantly differs from a normal distribution\n\n"
    )
  } else if (!is.null(shapiro_result$p.value) &&
             shapiro_result$p.value <= 0.05) {
    cat(
      "Reject the null hypothesis that data significantly differs from a normal distribution\n\n"
    )
  } else {
    cat("Unable to compute p-value for the test.\n\n")
  }
}

```

### b. Homogeneity of Variance
```{r, warning = FALSE}

# Levene's test for homoscedasticity (homogeneity of variance)

stat_lResults <- list() # empty list to store results

# Levene's test for-loop, going through each indexed column
for (pair in groupPairs) {
  
  # printing the pair to see the comparison
  print(pair)
  
  # extracting the pair!
  group1 <- df[[pair[1]]] # member no. 1 of pair!
  group2 <- df[[pair[2]]] # member no. 2 of pair!
  
  # performing Levene's test
  lResults <-
    leveneTest(group1, group2) # funky naming to deal with overwriting issues :/
  
  # storing results in the pre-established list
  test_name <- paste("Levene test between", pair[1], "and", pair[2])
  stat_lResults[[test_name]] <- lResults
  
  # see the result!
  cat(test_name, ":\n")
  print(lResults)
  
  # performing the hypothesis test using results!
  if (!is.null(lResults$`Pr(>F)`[1]) &&
      lResults$`Pr(>F)`[1] > 0.05) {
    cat(
      "Fail to reject null hypothesis that there is no significant difference between the groups\n\n"
    )
  } else if (!is.null(lResults$`Pr(>F)`[1]) &&
             lResults$`Pr(>F)`[1] <= 0.05) {
    cat(
      "Reject the null hypothesis that there is no significant difference between the groups\n\n"
    )
  } else {
    cat("Unable to compute p-value for the test.\n\n")
  }
}

```

## 2.2. Stat. Testing!
### a. Paired t-Test
```{r}

# paired t-Tests comparing pre-tool and post-tool usage !

stat_tResults <- list() # empty list to store the results

# Paired t-Test for-loop, iterating through each indexed column
for (pair in groupPairs) {
  
  # extracting the group pairs and performing numeric conversions where necessary
  group1 <- as.numeric(c(df[[pair[1]]]))
  group2 <- as.numeric(c(df[[pair[2]]]))
  
  # perfomring the paired t-test!
  stat_tResults <- t.test(group1, group2, paired = TRUE,
                          alternative = "two.sided")
  
  # storing the result in the pre-established list!
  test_name <- paste("Paired t-test between", pair[1], "and", pair[2])
  stat_tResults[[test_name]] <- stat_tResults
  
  # seeing the result of our lovely test!
  cat(test_name, ":\n")
  print(stat_tResults)
  
  # performing the hypothesis test using results!
  if (!is.null(stat_tResults$p.value[1]) && stat_tResults$p.value[1] > 0.05) {
    cat("Fail to reject null hypothesis that there is no significant difference between the groups\n\n")
  } else if (!is.null(stat_tResults$p.value[1]) && stat_tResults$p.value[1] <= 0.05) {
    cat("Reject the null hypothesis that there is no significant difference between the groups\n\n")
  } else {
    cat("Unable to compute p-value for the test.\n\n")
  }
}

```

### b. Non-Parametric Paired t-test (?)
```{r}

# non-parametric stuff for groups that don't meet parametric assumptions

```


## 2.2. Graphing
```{r}

# pre-tool vs. post tool usage -- bias perception (BP)
compHisto_dfBiasPerception <- grPlot_dfBiasPerception %>%
  ggplot(aes(x = measure, fill = group)) +
  geom_histogram(position = "identity",
                 alpha = 0.5,
                 bins = 10) +
  labs(title = "Pre- vs. Post-Tool Self-Scores of Bias Perception (BP)",
       x = "Self-Score (1 - 10) of Own Bias Perception", y = "Frequency") +
  scale_fill_manual(values = c("Pre-Tool BP" = "blue", "Post-Tool BP" = "red")) +
  theme_minimal()
compHisto_dfBiasPerception

# pre-tool vs. post tool usage -- bias awareness (BA)
compHisto_dfBiasAwareness <- grPlot_dfBiasAwareness %>%
  ggplot(aes(x = measure, fill = group)) +
  geom_histogram(position = "identity",
                 alpha = 0.5,
                 bins = 10) +
  labs(title = "Pre- vs. Post-Tool Self-Scores of Bias Awareness",
       x = "Self-Score (1 - 10) of Own Bias Awareness (BA)", y = "Frequency") +
  scale_fill_manual(values = c("Pre-Tool BA" = "blue", "Post-Tool BA" = "red")) +
  theme_minimal()
compHisto_dfBiasAwareness

# pre-tool vs. post tool usage -- morality (M)
compHisto_dfMorality <- grPlot_dfMorality %>%
  ggplot(aes(x = measure, fill = group)) +
  geom_histogram(position = "identity",
                 alpha = 0.5,
                 bins = 10) +
  labs(title = "Pre- vs. Post-Tool Self-Scores of Morality",
       x = "Self-Score (1 - 10) of Own Morality (M)", y = "Frequency") +
  scale_fill_manual(values = c("Pre-Tool M" = "blue", "Post-Tool M" = "red")) +
  theme_minimal()
compHisto_dfMorality

# pre-tool vs. post tool usage -- value commitment (VC)
compHisto_dfValCommitment <- grPlot_dfValCommitment %>%
  ggplot(aes(x = measure, fill = group)) +
  geom_histogram(position = "identity",
                 alpha = 0.5,
                 bins = 10) +
  labs(title = "Pre- vs. Post-Tool Self-Scores of Value Commitment ",
       x = "Self-Score (1 - 10) of Own Value Commitment (VC)", y = "Frequency") +
  scale_fill_manual(values = c("Pre-Tool VC" = "blue", "Post-Tool VC" = "red")) +
  theme_minimal()
compHisto_dfValCommitment

plots_preXpost <- compHisto_dfBiasAwareness / compHisto_dfBiasAwareness / compHisto_dfMorality / compHisto_dfValCommitment

plots_preXpost

```


# 3. Unused Code I'm Too Paranoid to Delete
```{r, message = FALSE}

# pasting sample size
### this doesn't even need to be saved, at this point idk
print(paste("N =", nrow(df)))

# - - - -

# making all text in df lowercase
df <- df %>%
  mutate(
    vote_eligibility = tolower(vote_eligibility),
    char_engagement = tolower(char_engagement),
    char_ranking_selfperception = tolower(char_engagement),
    char_past_candidate_test = tolower(char_past_candidate_test),
    char_future_candidate_test = tolower(char_future_candidate_test),
    char_comment_tool_selfperception = tolower(char_comment_tool_selfperception),
    char_comment_tool_design = tolower(char_comment_tool_design),
    char_comment_other = tolower(char_comment_other),
    gender = tolower(gender)
  )

# - - - - 

```

